# multilayered perceptrons
creating a neural networkd having

input-2 parametes
output-2 parameters
2 hidden layers with 4 and 3 neurons respectively

In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [46]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [47]:
def softmax(a):
    exp_a=np.exp(a)
    exp_sum=np.sum(exp_a,axis=1,keepdims=True)
    return exp_a/exp_sum
    

In [48]:
input_size=2
output_size=2
hidden=[4,3]

In [75]:
class NeuralNetwork:
    def __init__(self,input_size,output_size,hidden):
        model={}# dictionary
        """
        input layer--(W1,B1)-->layer1--(W2,B2)-->layer2--(W3,B3)-->output layer
        """
        
        # from input layer to layer 1
        model['W1']=np.random.randn(input_size,hidden[0])
        model['B1']=np.random.randn(1,hidden[0])
        
        # from layer 1 to layer 2
        model['W2']=np.random.randn(hidden[0],hidden[1])
        model['B2']=np.random.randn(1,hidden[1])
        
        # from  layer 2 to output layer
        model['W3']=np.random.randn(hidden[1],output_size)
        model['B3']=np.random.randn(1,output_size)
        
        """
        for x in model:
            print(x,model[x].shape)
        """
        self.model=model
    def forward_propagation(self,X):
        """
        X--> Matrix of size m X n where m is the no of examples and n=input_size
        """
        model=self.model
        W1,W2,W3=model['W1'],model['W2'],model['W3']
        b1,b2,b3=model['B1'],model['B2'],model['B3']
        
        z1=np.dot(X,W1)+b1
        a1=sigmoid(z1)
        
        z2=np.dot(z1,W2)+b2
        a2=sigmoid(z2)
        
        z3=np.dot(z2,W3)+b3
        a3=softmax(z3)
       # print(a3)
        #print(a3.sum(axis=1))
        
        
        
        

In [72]:
myModel=NeuralNetwork(input_size,output_size,hidden)

In [73]:
x=np.array([[10,10],[10,20],[11,230],[1,10]])
print(softmax(x))
print(np.sum(softmax(x),axis=1))
        

[[5.00000000e-01 5.00000000e-01]
 [4.53978687e-05 9.99954602e-01]
 [7.75369053e-96 1.00000000e+00]
 [1.23394576e-04 9.99876605e-01]]
[1. 1. 1. 1.]


In [74]:
x=np.array([[1,2],[3,4],[5,6]])
myModel.forward_propagation(x)

[[9.99999992e-01 8.06625703e-09]
 [1.00000000e+00 2.30663921e-21]
 [1.00000000e+00 6.59610077e-34]]
[1. 1. 1.]


In [66]:
print(x)

[[1 2]
 [3 4]
 [5 6]]
