# multilayered perceptrons
creating a neural networkd having

input-2 parametes
output-2 parameters
2 hidden layers with 4 and 3 neurons respectively

In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def softmax(a):
    exp_a=np.exp(a)
    exp_sum=np.sum(exp_a,axis=1,keepdims=True)
    return exp_a/exp_sum
    

In [4]:
input_size=2
output_size=2
hidden=[4,3]

In [12]:
class NeuralNetwork:
    def __init__(self,input_size,output_size,hidden):
        model={}# dictionary
        """
        input layer--(W1,B1)-->layer1--(W2,B2)-->layer2--(W3,B3)-->output layer
        """
        
        # from input layer to layer 1
        model['W1']=np.random.randn(input_size,hidden[0])
        model['B1']=np.random.randn(1,hidden[0])
        
        # from layer 1 to layer 2
        model['W2']=np.random.randn(hidden[0],hidden[1])
        model['B2']=np.random.randn(1,hidden[1])
        
        # from  layer 2 to output layer
        model['W3']=np.random.randn(hidden[1],output_size)
        model['B3']=np.random.randn(1,output_size)
        
        """
        for x in model:
            print(x,model[x].shape)
        """
        self.model=model
    def forward_propagation(self,X):
        """
        X--> Matrix of size m X n where m is the no of examples and n=input_size
        """
        model=self.model
        W1,W2,W3=model['W1'],model['W2'],model['W3']
        b1,b2,b3=model['B1'],model['B2'],model['B3']
        
        z1=np.dot(X,W1)+b1
        a1=sigmoid(z1)
        
        z2=np.dot(z1,W2)+b2
        a2=sigmoid(z2)
        
        z3=np.dot(z2,W3)+b3
        a3=softmax(z3)
        #print(a3)
        #print(a3.sum(axis=1))
        self.activations=(a1,a1,a3)
        return a3
        
    def backward_propagation(self,x,y,learning_rate=0.001):
        model=self.model
        W1,W2,W3=model['W1'],model['W2'],model['W3']
        b1,b2,b3=model['B1'],model['B2'],model['B3']
        (a1,a2,a3)=self.activations
        
        m=x.shape[0]
        
        delta3=a3-y
        dw3=np.dot(a2.T,delta3)
        db3=np.sum(delta3,axis=0)/m
        
        delta2=np.dot(delta3,W3.T)*a2*(1-a2)
        dw2=np.dot(a1.T,delta2)
        db2=np.sum(delta2,axis=0)/m
        
        
        delta1=np.dot(delta2,W2.T)*a1*(1-a1)
        dw1=np.dot(x.T,delta1)
        db1=np.sum(delta1,axis=0)/m
        
        # update
        model["W3"]-=learning_rate*dw3
        model["B3"]-=learning_rate*db3
        
        model["W2"]-=learning_rate*dw2
        model["B2"]-=learning_rate*db2
        
        model["W1"]-=learning_rate*dw1
        model["B1"]-=learning_rate*db1


    def predict(x):
        y_=self.forward_propagation(x)
        return np.argmax(x,axis=1);
        
        

        

In [6]:
myModel=NeuralNetwork(input_size,output_size,hidden)

In [7]:
x=np.array([[10,10],[10,20],[11,230],[1,10]])
print(softmax(x))
print(np.sum(softmax(x),axis=1))
        

[[5.00000000e-01 5.00000000e-01]
 [4.53978687e-05 9.99954602e-01]
 [7.75369053e-96 1.00000000e+00]
 [1.23394576e-04 9.99876605e-01]]
[1. 1. 1. 1.]


In [8]:
x=np.array([[1,2],[3,4],[5,6]])
myModel.forward_propagation(x)

[[9.99993921e-01 6.07890940e-06]
 [1.00000000e+00 2.00806107e-11]
 [1.00000000e+00 6.63323712e-17]]


In [9]:
print(x)

[[1 2]
 [3 4]
 [5 6]]
